### ISSUE TITLE
Quick Look & Copy Code Buttons Not Visible

### ISSUE THREAD

**Issue by vijaybhaskar14** [bridgedxyz/assistant#78]
I had recently tried this plugin every thing cool but i found that **Quick Look & Copy Code Buttons are Not Visible to me** firstly i thought its my laptop screen size issue then i had tried other laptop also and i faced same issue again  . im attaching screenshot here please find that get me the solution why its happening to me
![image](https://user-images.githubusercontent.com/34467495/107747309-3be18480-6d3d-11eb-9dc5-60ce0c48bf54.png)

**Comment by softmarshmallow** [comment]
@vijaybhaskar14 Can you share us your physical / actual pixel resolutions on your display?

We'll see if we can support that screen size your using.

One temporary solution is to use figma on the web, make chrome or other browser that you using to zoom down, then it will be visible.


As you can see, the buttons are visible below as you might understand whats happening here.
![image](https://user-images.githubusercontent.com/16307013/107747664-2a0eda00-6d5b-11eb-8e8a-9346edf6e259.png)

**Comment by vijaybhaskar14** [comment]
Hey , I had tried this in **figma web** to but same issue raised & I'm using 1366x768 resolution screen


(Are you using zoomed display? such as display content preference or magnifier features on windows) : No im using recommended from the windows

you can find the attachment below
![Capture](https://user-images.githubusercontent.com/34467495/107749570-d099b180-6d40-11eb-9e27-d9756dc16585.PNG)

**Comment by softmarshmallow** [comment]
Understood. since 1366x768 is rare display these days so the priority will not be on top. Thus I'm on the research to how to implement responsive ui on figma plugin, which is tricky because `window` does not exists until we tell figma to draw a window with specified size.

So... we'll need a nodejs (non browser api) api to read physical display size or figma canvas size, then draw the plugin ui.
Other option is to provide on settings enabling user to select which plugin size they would like to use.
Third, (not likely) is to adjust whole design to no go bigger than height of 480. (since figma's editor ui charges some heights, left space for plugin seems like around 480 ~ 600) -- which we cannot make a good design out of it.

Actually, this seems like a figma's bug that the height should be forced down to fit relative to physical screen size. this is how browser works.

**Comment by vijaybhaskar14** [comment]
ok and one more thing .. is this bridged completely have the no code write feature(means no need write code manually for alignments , color backgrounds & layout corrections ) ?? or we can modify code manually ??
coz i had tried XD to Flutter also (actually we can do lot of manual work in xd to flutter ) is this same way to  bridged??

**Comment by softmarshmallow** [comment]
This should be discussed in a new thread. Could you open up new issue for this? I can explain our plans & tech & features for above questions.

**Comment by vijaybhaskar14** [comment]
sure
